p8105_hw2_ml5308
================
Mutian Li
2025-10-01

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

``` r
pols_month <- read_csv("fivethirtyeight_datasets/pols-month.csv")
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month
```

    ## # A tibble: 822 × 9
    ##    mon        prez_gop gov_gop sen_gop rep_gop prez_dem gov_dem sen_dem rep_dem
    ##    <date>        <dbl>   <dbl>   <dbl>   <dbl>    <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947-01-15        0      23      51     253        1      23      45     198
    ##  2 1947-02-15        0      23      51     253        1      23      45     198
    ##  3 1947-03-15        0      23      51     253        1      23      45     198
    ##  4 1947-04-15        0      23      51     253        1      23      45     198
    ##  5 1947-05-15        0      23      51     253        1      23      45     198
    ##  6 1947-06-15        0      23      51     253        1      23      45     198
    ##  7 1947-07-15        0      23      51     253        1      23      45     198
    ##  8 1947-08-15        0      23      51     253        1      23      45     198
    ##  9 1947-09-15        0      23      51     253        1      23      45     198
    ## 10 1947-10-15        0      23      51     253        1      23      45     198
    ## # ℹ 812 more rows

``` r
dim(pols_month)
```

    ## [1] 822   9

``` r
pols_month_cleaned <- pols_month %>%
  separate(mon, into = c("year","month","day"), convert = TRUE) %>%
  mutate(
    month = tolower(month.name[month]),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem",
      TRUE ~ NA_character_
    )
  ) %>%
  select(-day, -prez_gop, -prez_dem)

pols_month_cleaned
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 january        23      51     253      23      45     198 dem      
    ##  2  1947 february       23      51     253      23      45     198 dem      
    ##  3  1947 march          23      51     253      23      45     198 dem      
    ##  4  1947 april          23      51     253      23      45     198 dem      
    ##  5  1947 may            23      51     253      23      45     198 dem      
    ##  6  1947 june           23      51     253      23      45     198 dem      
    ##  7  1947 july           23      51     253      23      45     198 dem      
    ##  8  1947 august         23      51     253      23      45     198 dem      
    ##  9  1947 september      23      51     253      23      45     198 dem      
    ## 10  1947 october        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

``` r
snp <- read_csv("fivethirtyeight_datasets/snp.csv")
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp
```

    ## # A tibble: 787 × 2
    ##    date    close
    ##    <chr>   <dbl>
    ##  1 7/1/15  2080.
    ##  2 6/1/15  2063.
    ##  3 5/1/15  2107.
    ##  4 4/1/15  2086.
    ##  5 3/2/15  2068.
    ##  6 2/2/15  2104.
    ##  7 1/2/15  1995.
    ##  8 12/1/14 2059.
    ##  9 11/3/14 2068.
    ## 10 10/1/14 2018.
    ## # ℹ 777 more rows

``` r
dim(snp)
```

    ## [1] 787   2

``` r
snp_cleaned <- snp %>% 
  mutate(date = mdy(date)) %>% 
  separate(date, into = c("year","month","day"), convert = TRUE) %>% 
  mutate(month = tolower(month.name[month])) %>% 
  select(year, month, close) %>% 
  arrange(year, match(month, tolower(month.name)))

snp_cleaned
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <int> <chr>     <dbl>
    ##  1  1969 january   103. 
    ##  2  1969 february   98.1
    ##  3  1969 march     102. 
    ##  4  1969 april     104. 
    ##  5  1969 may       103. 
    ##  6  1969 june       97.7
    ##  7  1969 july       91.8
    ##  8  1969 august     95.5
    ##  9  1969 september  93.1
    ## 10  1969 october    97.1
    ## # ℹ 777 more rows

``` r
unemployment <- read_csv("fivethirtyeight_datasets/unemployment.csv")
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment
```

    ## # A tibble: 68 × 13
    ##     Year   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
    ##    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
    ##  1  1948   3.4   3.8   4     3.9   3.5   3.6   3.6   3.9   3.8   3.7   3.8   4  
    ##  2  1949   4.3   4.7   5     5.3   6.1   6.2   6.7   6.8   6.6   7.9   6.4   6.6
    ##  3  1950   6.5   6.4   6.3   5.8   5.5   5.4   5     4.5   4.4   4.2   4.2   4.3
    ##  4  1951   3.7   3.4   3.4   3.1   3     3.2   3.1   3.1   3.3   3.5   3.5   3.1
    ##  5  1952   3.2   3.1   2.9   2.9   3     3     3.2   3.4   3.1   3     2.8   2.7
    ##  6  1953   2.9   2.6   2.6   2.7   2.5   2.5   2.6   2.7   2.9   3.1   3.5   4.5
    ##  7  1954   4.9   5.2   5.7   5.9   5.9   5.6   5.8   6     6.1   5.7   5.3   5  
    ##  8  1955   4.9   4.7   4.6   4.7   4.3   4.2   4     4.2   4.1   4.3   4.2   4.2
    ##  9  1956   4     3.9   4.2   4     4.3   4.3   4.4   4.1   3.9   3.9   4.3   4.2
    ## 10  1957   4.2   3.9   3.7   3.9   4.1   4.3   4.2   4.1   4.4   4.5   5.1   5.2
    ## # ℹ 58 more rows

``` r
dim(unemployment)
```

    ## [1] 68 13

``` r
unemployment_cleaned <- unemployment %>% 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) %>% 
  mutate(
    month = tolower(month.name[match(month, month.abb)])
  ) %>% 
  rename(year = Year) %>%
  arrange(year, match(month, tolower(month.name)))

unemployment_cleaned
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 january            3.4
    ##  2  1948 february           3.8
    ##  3  1948 march              4  
    ##  4  1948 april              3.9
    ##  5  1948 may                3.5
    ##  6  1948 june               3.6
    ##  7  1948 july               3.6
    ##  8  1948 august             3.9
    ##  9  1948 september          3.8
    ## 10  1948 october            3.7
    ## # ℹ 806 more rows

``` r
merged_data <- pols_month_cleaned %>%
  left_join(snp_cleaned, by = c("year", "month")) %>%
  left_join(unemployment_cleaned, by = c("year", "month"))

merged_data
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 january      23      51     253      23      45     198 dem          NA
    ##  2  1947 februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 march        23      51     253      23      45     198 dem          NA
    ##  4  1947 april        23      51     253      23      45     198 dem          NA
    ##  5  1947 may          23      51     253      23      45     198 dem          NA
    ##  6  1947 june         23      51     253      23      45     198 dem          NA
    ##  7  1947 july         23      51     253      23      45     198 dem          NA
    ##  8  1947 august       23      51     253      23      45     198 dem          NA
    ##  9  1947 septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 october      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

The pols-month.csv file contains 822 monthly observations between 1947
and 2015, describing the number of national politicians (governors,
senators, and representatives) by party affiliation, along with the
party of the sitting president. The snp.csv file contains 787 monthly
observations from 1950 to 2015, which is the closing values of the
Standard & Poor’s stock market index (S&P). The unemployment.csv file
contains 816 monthly observations between 1948 and 2015, reporting the
percentage of unemployment for each month.

After cleaning and tidying, these datasets were merged by year and
month, resulting in a unified dataset that contains political variables
(party of president and counts of governors, senators, and
representatives), economic indicators (S&P index values), and employment
data (monthly unemployment rates). This merged dataset allows for
analyses of the relationships between political leadership and economic
performance over time.

## Problem 2

``` r
library(readxl)
```

``` r
mr_trash_wheel <- read_excel("202509 Trash Wheel Collection Data.xlsx", 
                             sheet = "Mr. Trash Wheel", 
                             skip = 1) %>%
  janitor::clean_names() %>%
  select(-starts_with("x")) %>%
  filter(!is.na(dumpster)) %>%
  separate(date, into = c("year","month","day"), convert = TRUE) %>% 
  mutate(sports_balls = as.integer(round(sports_balls)),
         source = "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_trash_wheel
```

    ## # A tibble: 707 × 15
    ##    dumpster  year month   day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <int> <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2014     5    16        4.31                 18            1450
    ##  2        2  2014     5    16        2.74                 13            1120
    ##  3        3  2014     5    16        3.45                 15            2450
    ##  4        4  2014     5    17        3.1                  15            2380
    ##  5        5  2014     5    17        4.06                 18             980
    ##  6        6  2014     5    20        2.71                 13            1430
    ##  7        7  2014     5    21        1.91                  8             910
    ##  8        8  2014     5    28        3.7                  16            3580
    ##  9        9  2014     6     5        2.52                 14            2400
    ## 10       10  2014     6    11        3.76                 18            1340
    ## # ℹ 697 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, source <chr>

``` r
prof_trash_wheel <- read_excel("202509 Trash Wheel Collection Data.xlsx",
                               sheet = "Professor Trash Wheel",
                               skip = 1) %>%
  janitor::clean_names() %>%
  filter(!is.na(date)) %>%
  separate(date, into = c("year","month","day"), convert = TRUE) %>% 
  mutate(
    source = "Professor Trash Wheel"
  )

prof_trash_wheel
```

    ## # A tibble: 132 × 14
    ##    dumpster  year month   day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <int> <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2017     1     2        1.79                 15            1950
    ##  2        2  2017     1    30        1.58                 15            9540
    ##  3        3  2017     2    26        2.32                 18            8350
    ##  4        4  2017     2    26        3.72                 15            8590
    ##  5        5  2017     2    28        1.45                 15            7830
    ##  6        6  2017     3    30        1.71                 15            8210
    ##  7        7  2017     4     1        1.82                 15            9830
    ##  8        8  2017     4    20        2.37                 15            9240
    ##  9        9  2017     5    10        2.64                 15            9540
    ## 10       10  2017     5    26        2.78                 15            8230
    ## # ℹ 122 more rows
    ## # ℹ 7 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, source <chr>

``` r
gwynns_trash_wheel <- read_excel("202509 Trash Wheel Collection Data.xlsx",
                                 sheet = "Gwynns Falls Trash Wheel",
                                 skip = 1) %>%
  janitor::clean_names() %>%
  filter(!is.na(date)) %>%
  separate(date, into = c("year","month","day"), convert = TRUE) %>% 
  mutate(
    source = "Gwynns Falls Trash Wheel"
  )

gwynns_trash_wheel
```

    ## # A tibble: 349 × 13
    ##    dumpster  year month   day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <int> <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2021     7     3        0.93                 15            1200
    ##  2        2  2021     7     7        2.26                 15            2000
    ##  3        3  2021     7     7        1.62                 15            1800
    ##  4        4  2021     7    16        1.76                 15            1000
    ##  5        5  2021     7    30        1.53                 15            2100
    ##  6        6  2021     8    11        2.06                 15            2400
    ##  7        7  2021     8    14        1.9                  15            2700
    ##  8        8  2021     8    16        2.16                 15            3000
    ##  9        9  2021     8    16        2.6                  15             980
    ## 10       10  2021     8    17        3.21                 15             240
    ## # ℹ 339 more rows
    ## # ℹ 6 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>, source <chr>

``` r
all_trash <- bind_rows(mr_trash_wheel,
                       prof_trash_wheel,
                       gwynns_trash_wheel)
all_trash
```

    ## # A tibble: 1,188 × 15
    ##    dumpster  year month   day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <int> <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2014     5    16        4.31                 18            1450
    ##  2        2  2014     5    16        2.74                 13            1120
    ##  3        3  2014     5    16        3.45                 15            2450
    ##  4        4  2014     5    17        3.1                  15            2380
    ##  5        5  2014     5    17        4.06                 18             980
    ##  6        6  2014     5    20        2.71                 13            1430
    ##  7        7  2014     5    21        1.91                  8             910
    ##  8        8  2014     5    28        3.7                  16            3580
    ##  9        9  2014     6     5        2.52                 14            2400
    ## 10       10  2014     6    11        3.76                 18            1340
    ## # ℹ 1,178 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, source <chr>

``` r
nrow(all_trash)
```

    ## [1] 1188

``` r
prof_trash_wheel %>%
  summarise(total_weight_tons = sum(weight_tons, na.rm = TRUE))
```

    ## # A tibble: 1 × 1
    ##   total_weight_tons
    ##               <dbl>
    ## 1              282.

``` r
gwynns_trash_wheel %>%
  filter(year == 2022, month == 6) %>%
  summarise(total_cig_butts = sum(cigarette_butts, na.rm = TRUE))
```

    ## # A tibble: 1 × 1
    ##   total_cig_butts
    ##             <dbl>
    ## 1           18120

After cleaning and combining the datasets from Mr. Trash Wheel,
Professor Trash Wheel, and Gwynns Falls Trash Wheel, the resulting
dataset contains 1188 observations. Key variables include the date of
collection (`year`, `month`, `day`), the amount of trash collected in
tons (`weight_tons`), and counts of common items such as plastic
bottles, polystyrene, cigarette butts, glass bottles, and plastic bags.
For example, the total weight of trash collected by Professor Trash
Wheel was 282.26 tons. In addition, Gwynns Falls Trash Wheel collected 0
cigarette butts in June of 2022.

## Problem 3

``` r
zip_info <- read_csv("zillow_data/Zip Codes.csv")
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zillow <- read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zip_info
```

    ## # A tibble: 322 × 7
    ##    County `State FIPS` `County Code` `County FIPS` ZipCode `File Date`
    ##    <chr>         <dbl> <chr>                 <dbl>   <dbl> <chr>      
    ##  1 Bronx            36 005                   36005   10451 7/25/07    
    ##  2 Bronx            36 005                   36005   10452 7/25/07    
    ##  3 Bronx            36 005                   36005   10453 7/25/07    
    ##  4 Bronx            36 005                   36005   10454 7/25/07    
    ##  5 Bronx            36 005                   36005   10455 7/25/07    
    ##  6 Bronx            36 005                   36005   10456 7/25/07    
    ##  7 Bronx            36 005                   36005   10457 7/25/07    
    ##  8 Bronx            36 005                   36005   10458 7/25/07    
    ##  9 Bronx            36 005                   36005   10459 7/25/07    
    ## 10 Bronx            36 005                   36005   10460 7/25/07    
    ## # ℹ 312 more rows
    ## # ℹ 1 more variable: Neighborhood <chr>

``` r
zillow
```

    ## # A tibble: 149 × 125
    ##    RegionID SizeRank RegionName RegionType StateName State City     Metro       
    ##       <dbl>    <dbl>      <dbl> <chr>      <chr>     <chr> <chr>    <chr>       
    ##  1    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  2    62093        7      11385 zip        NY        NY    New York New York-Ne…
    ##  3    62019        9      11208 zip        NY        NY    New York New York-Ne…
    ##  4    62046       16      11236 zip        NY        NY    New York New York-Ne…
    ##  5    61807       17      10467 zip        NY        NY    New York New York-Ne…
    ##  6    62085       18      11373 zip        NY        NY    New York New York-Ne…
    ##  7    62037       19      11226 zip        NY        NY    New York New York-Ne…
    ##  8    62018       20      11207 zip        NY        NY    New York New York-Ne…
    ##  9    61639       29      10025 zip        NY        NY    New York New York-Ne…
    ## 10    62025       32      11214 zip        NY        NY    New York New York-Ne…
    ## # ℹ 139 more rows
    ## # ℹ 117 more variables: CountyName <chr>, `2015-01-31` <dbl>,
    ## #   `2015-02-28` <dbl>, `2015-03-31` <dbl>, `2015-04-30` <dbl>,
    ## #   `2015-05-31` <dbl>, `2015-06-30` <dbl>, `2015-07-31` <dbl>,
    ## #   `2015-08-31` <dbl>, `2015-09-30` <dbl>, `2015-10-31` <dbl>,
    ## #   `2015-11-30` <dbl>, `2015-12-31` <dbl>, `2016-01-31` <dbl>,
    ## #   `2016-02-29` <dbl>, `2016-03-31` <dbl>, `2016-04-30` <dbl>, …

``` r
zillow_long <- zillow %>%
  pivot_longer(
    cols = matches("^20"),
    names_to = "date",
    values_to = "rent_price"
  ) %>%
  mutate(date = as.Date(date))

zillow_long
```

    ## # A tibble: 17,284 × 11
    ##    RegionID SizeRank RegionName RegionType StateName State City     Metro       
    ##       <dbl>    <dbl>      <dbl> <chr>      <chr>     <chr> <chr>    <chr>       
    ##  1    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  2    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  3    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  4    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  5    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  6    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  7    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  8    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  9    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ## 10    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ## # ℹ 17,274 more rows
    ## # ℹ 3 more variables: CountyName <chr>, date <date>, rent_price <dbl>

``` r
final_data <- zillow_long %>%
  left_join(zip_info, by = c("RegionName" = "ZipCode"))
```

    ## Warning in left_join(., zip_info, by = c(RegionName = "ZipCode")): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 4757 of `x` matches multiple rows in `y`.
    ## ℹ Row 256 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

``` r
final_data
```

    ## # A tibble: 17,516 × 17
    ##    RegionID SizeRank RegionName RegionType StateName State City     Metro       
    ##       <dbl>    <dbl>      <dbl> <chr>      <chr>     <chr> <chr>    <chr>       
    ##  1    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  2    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  3    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  4    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  5    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  6    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  7    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  8    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ##  9    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ## 10    62080        4      11368 zip        NY        NY    New York New York-Ne…
    ## # ℹ 17,506 more rows
    ## # ℹ 9 more variables: CountyName <chr>, date <date>, rent_price <dbl>,
    ## #   County <chr>, `State FIPS` <dbl>, `County Code` <chr>, `County FIPS` <dbl>,
    ## #   `File Date` <chr>, Neighborhood <chr>

``` r
nrow(final_data)
```

    ## [1] 17516

``` r
n_distinct(final_data$RegionName)
```

    ## [1] 149

``` r
n_distinct(final_data$Neighborhood)
```

    ## [1] 43

``` r
setdiff(zip_info$ZipCode, zillow$RegionName)
```

    ##   [1] 10464 10474 10475 10499 10550 10704 10705 10803 11202 11224 11239 11241
    ##  [13] 11242 11243 11245 11247 11251 11252 11256 10008 10020 10041 10043 10045
    ##  [25] 10047 10048 10055 10072 10080 10081 10082 10087 10101 10102 10103 10104
    ##  [37] 10105 10106 10107 10108 10109 10110 10111 10112 10113 10114 10115 10116
    ##  [49] 10117 10118 10119 10120 10121 10122 10123 10124 10125 10126 10129 10130
    ##  [61] 10131 10132 10133 10138 10149 10150 10151 10152 10153 10154 10155 10156
    ##  [73] 10157 10158 10159 10160 10161 10163 10164 10165 10166 10167 10168 10169
    ##  [85] 10170 10171 10172 10173 10174 10175 10176 10177 10178 10179 10185 10197
    ##  [97] 10199 10213 10242 10249 10256 10259 10260 10261 10265 10268 10269 10270
    ## [109] 10271 10272 10273 10274 10275 10276 10277 10278 10279 10281 10285 10286
    ## [121] 10292 11001 11004 11005 11040 11096 11351 11352 11359 11362 11363 11371
    ## [133] 11380 11381 11386 11405 11411 11412 11413 11414 11416 11417 11419 11420
    ## [145] 11421 11422 11423 11424 11425 11427 11428 11429 11430 11431 11433 11436
    ## [157] 11439 11451 11499 11559 11580 11690 11694 11695 11697 10302 10307 10309
    ## [169] 10310 10311 10313

ZIP codes such as 10101, 10118, and 10499 appear in the mapping dataset
but are not included in Zillow’s rental data.

``` r
covid_change <- final_data %>%
  filter(date %in% c("2020-01-31","2021-01-31")) %>%
  pivot_wider(names_from = date, values_from = rent_price) %>%
  mutate(drop = (`2021-01-31` - `2020-01-31`) / `2020-01-31`) %>%
  arrange(drop) %>%
  slice_head(n=10)

covid_change
```

    ## # A tibble: 10 × 18
    ##    RegionID SizeRank RegionName RegionType StateName State City     Metro       
    ##       <dbl>    <dbl>      <dbl> <chr>      <chr>     <chr> <chr>    <chr>       
    ##  1    61618    30490      10004 zip        NY        NY    New York New York-Ne…
    ##  2    61623      531      10009 zip        NY        NY    New York New York-Ne…
    ##  3    61652     5069      10038 zip        NY        NY    New York New York-Ne…
    ##  4    61616      139      10002 zip        NY        NY    New York New York-Ne…
    ##  5    61630      872      10016 zip        NY        NY    New York New York-Ne…
    ##  6    61626     5253      10012 zip        NY        NY    New York New York-Ne…
    ##  7    61617      710      10003 zip        NY        NY    New York New York-Ne…
    ##  8    61624     2896      10010 zip        NY        NY    New York New York-Ne…
    ##  9    61650     4279      10036 zip        NY        NY    New York New York-Ne…
    ## 10    61636     2723      10022 zip        NY        NY    New York New York-Ne…
    ## # ℹ 10 more variables: CountyName <chr>, County <chr>, `State FIPS` <dbl>,
    ## #   `County Code` <chr>, `County FIPS` <dbl>, `File Date` <chr>,
    ## #   Neighborhood <chr>, `2020-01-31` <dbl>, `2021-01-31` <dbl>, drop <dbl>

Rental prices dropped most sharply in Manhattan ZIP codes such as 10004
(Financial District) and 10009 (East Village).
